# Generated by Django 5.1.2 on 2024-11-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Firma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid_firma", models.TextField(default="n")),
                ("ip", models.CharField(max_length=255)),
                ("hora", models.TimeField()),
                ("fecha_firmado", models.DateField()),
                ("pdf_documento", models.CharField(max_length=255)),
                ("imagen_firma", models.CharField(max_length=255)),
            ],
        ),
    ]
