# Generated by Django 5.1.2 on 2024-11-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid_pdf", models.TextField()),
                ("nombre_cliente", models.TextField()),
                ("email_cliente", models.TimeField()),
                ("nombre_pdf", models.TextField()),
                ("firmado", models.BooleanField(default=False)),
                ("aprobado", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
