# Generated by Django 5.1.2 on 2024-11-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthInsuranceFormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("provincia", models.CharField(max_length=100)),
                ("asegurar", models.CharField(max_length=255)),
                ("edad", models.IntegerField()),
                ("aceptaProteccionDatos", models.BooleanField()),
                ("deseaPromociones", models.BooleanField()),
            ],
        ),
    ]
